In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [15]:
print ("Ayo cari transpose dari matriks berikut! ")
print ("=======================================")
matriks_awal_17 = np.random.randint(1,9,size=(5,5))
print ("matriks awal = ")
print (matriks_awal_17)

hasil_17 = input("\nApakah Anda sudah menemukan transposenya? Sudah/Belum")
if hasil_17 == 'Sudah':
    print("\nAyo cocokkan dengan jawaban berikut: ")
if hasil_17 == 'Belum':
    print("\nAyo temukan transpose dengan benar!")
    
print ("====================================")

matriks_transpose_17 = np.zeros((5,5))

for i in range(len(matriks_awal_17)):
    for j in range(len(matriks_awal_17[0])):
        matriks_transpose_17[j][i] = matriks_awal_17[i][j]

print ("matriks transpose = ")
for x in matriks_transpose_17 :
    print (x)

Ayo cari transpose dari matriks berikut! 
matriks awal = 
[[7 6 5 2 3]
 [5 4 7 6 6]
 [8 1 8 6 5]
 [5 7 7 7 1]
 [8 8 1 5 5]]



Apakah Anda sudah menemukan transposenya? Sudah/Belum Sudah



Ayo cocokkan dengan jawaban berikut: 
matriks transpose = 
[7. 5. 8. 5. 8.]
[6. 4. 1. 7. 8.]
[5. 7. 8. 7. 1.]
[2. 6. 6. 7. 5.]
[3. 6. 5. 1. 5.]


In [22]:
print("Selamat datang pada Program Pengoperasian Matriks Berpangkat!")
print("===============================================================")

baris_17 = int(input("Masukkan jumlah baris matriks: "))
kolom_17 = int(input("Masukkan jumlah kolom matriks: "))
print("==================================")

print("Masukkan elemen matriks:")
matriks_17 = []
for i in range(baris_17):
    row_17 = []
    for j in range(kolom_17):
        elemen_17 = float(input(f"Masukkan elemen baris {i+1} kolom {j+1}: "))
        row_17.append(elemen_17)
    matriks_17.append(row_17)
matriks_hasil_17 = np.array(matriks_17)
print(matriks_hasil_17)
print("=====================================")

pangkat_17 = int(input("Masukkan pangkat matriks: "))
print("Masukkan pangkat matriks: " + str(pangkat_17) )
matriks_akhir_17 = np.array(matriks_17)
hasil_pangkat_17 = np.linalg.matrix_power(matriks_akhir_17, pangkat_17)
print("=====================================")

print("Berikut hasil pangkat matriks yang Anda inginkan:")
print(hasil_pangkat_17)
print("\nTerimakasih telah menggunakan Program ini, semoga bermanfaat <3")


Selamat datang pada Program Pengoperasian Matriks Berpangkat!


Masukkan jumlah baris matriks:  2
Masukkan jumlah kolom matriks:  2


Masukkan elemen matriks:


Masukkan elemen baris 1 kolom 1:  1
Masukkan elemen baris 1 kolom 2:  2
Masukkan elemen baris 2 kolom 1:  3
Masukkan elemen baris 2 kolom 2:  4


[[1. 2.]
 [3. 4.]]


Masukkan pangkat matriks:  2


Masukkan pangkat matriks: 2
Berikut hasil pangkat matriks yang Anda inginkan:
[[ 7. 10.]
 [15. 22.]]

Terimakasih telah menggunakan Program ini, semoga bermanfaat <3
